In [67]:
import os
import pandas as pd 

PATH = '../../data/dogfacenet/aligned/'
df = pd.read_csv(PATH+'labels/via_region_data(7).csv')
df.head()

,filename,file_size,file_attributes,region_count,region_id,region_shape_attributes,region_attributes
0,272100.272100.jpg,28889,{},3,0,"{""name"":""point"",""cx"":122,""cy"":175}",{}
1,272100.272100.jpg,28889,{},3,1,"{""name"":""point"",""cx"":230,""cy"":185}",{}
2,272100.272100.jpg,28889,{},3,2,"{""name"":""point"",""cx"":149,""cy"":319}",{}
3,272100.272100_0.jpg,30813,{},3,0,"{""name"":""point"",""cx"":196,""cy"":161}",{}
4,272100.272100_0.jpg,30813,{},3,1,"{""name"":""point"",""cx"":287,""cy"":175}",{}

In [68]:
df2 = df[df.region_count == 3]

In [69]:
len(df2)/3

3177.0

In [70]:
df3 = df2[['filename','region_shape_attributes']]

In [71]:
df3.head()

              filename             region_shape_attributes
0    272100.272100.jpg  {"name":"point","cx":122,"cy":175}
1    272100.272100.jpg  {"name":"point","cx":230,"cy":185}
2    272100.272100.jpg  {"name":"point","cx":149,"cy":319}
3  272100.272100_0.jpg  {"name":"point","cx":196,"cy":161}
4  272100.272100_0.jpg  {"name":"point","cx":287,"cy":175}

In [72]:
from ast import literal_eval
df3['region_shape_attributes'] = df3['region_shape_attributes'].apply(literal_eval)

c:\users\guillaume\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [73]:
df3.head()

              filename                  region_shape_attributes
0    272100.272100.jpg  {'name': 'point', 'cx': 122, 'cy': 175}
1    272100.272100.jpg  {'name': 'point', 'cx': 230, 'cy': 185}
2    272100.272100.jpg  {'name': 'point', 'cx': 149, 'cy': 319}
3  272100.272100_0.jpg  {'name': 'point', 'cx': 196, 'cy': 161}
4  272100.272100_0.jpg  {'name': 'point', 'cx': 287, 'cy': 175}

In [74]:
df3['id'] = [i for i in range(len(df3))]

c:\users\guillaume\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [75]:
df3 = df3.set_index('id')

In [76]:
dic = df3['region_shape_attributes'][0]
dic

{'cx': 122, 'cy': 175, 'name': 'point'}

In [77]:
dic['cx']

122

In [78]:
df4 = pd.DataFrame(index=[i for i in range(len(df3)//3)],columns=['filename','lex','ley','rex','rey','nox','noy'])

In [79]:
df4['filename']=[df3['filename'][i] for i in range(0,len(df3),3)]
df4['lex'] = [df3['region_shape_attributes'][i]['cx'] for i in range(0,len(df3),3)]
df4['ley'] = [df3['region_shape_attributes'][i]['cy'] for i in range(0,len(df3),3)]
df4['rex'] = [df3['region_shape_attributes'][i]['cx'] for i in range(1,len(df3),3)]
df4['rey'] = [df3['region_shape_attributes'][i]['cy'] for i in range(1,len(df3),3)]
df4['nox'] = [df3['region_shape_attributes'][i]['cx'] for i in range(2,len(df3),3)]
df4['noy'] = [df3['region_shape_attributes'][i]['cy'] for i in range(2,len(df3),3)]

In [13]:
df3

                           filename                   region_shape_attributes
id
0                 272100.272100.jpg   {'name': 'point', 'cx': 122, 'cy': 175}
1                 272100.272100.jpg   {'name': 'point', 'cx': 230, 'cy': 185}
2                 272100.272100.jpg   {'name': 'point', 'cx': 149, 'cy': 319}
3               272100.272100_0.jpg   {'name': 'point', 'cx': 196, 'cy': 161}
4               272100.272100_0.jpg   {'name': 'point', 'cx': 287, 'cy': 175}
5               272100.272100_0.jpg   {'name': 'point', 'cx': 172, 'cy': 296}
6               272100.272100_1.jpg   {'name': 'point', 'cx': 404, 'cy': 125}
7               272100.272100_1.jpg   {'name': 'point', 'cx': 447, 'cy': 116}
8               272100.272100_1.jpg   {'name': 'point', 'cx': 441, 'cy': 177}
9               272100.272100_2.jpg    {'name': 'point', 'cx': 100, 'cy': 95}
10              272100.272100_2.jpg   {'name': 'point', 'cx': 155, 'cy': 103}
11              272100.272100_2.jpg   {'name': 'point', 'cx': 113, 'cy': 168}
12              272100.272100_4.jpg    {'name': 'point', 'cx': 158, 'cy': 75}
13              272100.272100_4.jpg    {'name': 'point', 'cx': 215, 'cy': 79}
14              272100.272100_4.jpg   {'name': 'point', 'cx': 177, 'cy': 139}
15              272100.272100_5.jpg    {'name': 'point', 'cx': 137, 'cy': 77}
16              272100.272100_5.jpg    {'name': 'point', 'cx': 186, 'cy': 80}
17              272100.272100_5.jpg   {'name': 'point', 'cx': 155, 'cy': 138}
18                272774.272774.jpg    {'name': 'point', 'cx': 167, 'cy': 97}
19                272774.272774.jpg    {'name': 'point', 'cx': 244, 'cy': 94}
20                272774.272774.jpg   {'name': 'point', 'cx': 187, 'cy': 157}
21             272774.272774_0.jpeg    {'name': 'point', 'cx': 233, 'cy': 81}
22             272774.272774_0.jpeg    {'name': 'point', 'cx': 269, 'cy': 81}
23             272774.272774_0.jpeg   {'name': 'point', 'cx': 240, 'cy': 128}
24              272774.272774_0.jpg   {'name': 'point', 'cx': 263, 'cy': 145}
25              272774.272774_0.jpg   {'name': 'point', 'cx': 323, 'cy': 141}
26              272774.272774_0.jpg   {'name': 'point', 'cx': 337, 'cy': 208}
27              272774.272774_1.jpg    {'name': 'point', 'cx': 173, 'cy': 60}
28              272774.272774_1.jpg    {'name': 'point', 'cx': 207, 'cy': 61}
29              272774.272774_1.jpg    {'name': 'point', 'cx': 177, 'cy': 87}
...                             ...                                       ...
9501     zack.i35873ce480b348e8.jpg   {'name': 'point', 'cx': 302, 'cy': 286}
9502     zack.i35873ce480b348e8.jpg   {'name': 'point', 'cx': 399, 'cy': 291}
9503     zack.i35873ce480b348e8.jpg   {'name': 'point', 'cx': 353, 'cy': 388}
9504  zdrafka.i3f0a0c3d8ed8b719.jpg   {'name': 'point', 'cx': 401, 'cy': 208}
9505  zdrafka.i3f0a0c3d8ed8b719.jpg   {'name': 'point', 'cx': 465, 'cy': 194}
9506  zdrafka.i3f0a0c3d8ed8b719.jpg   {'name': 'point', 'cx': 447, 'cy': 258}
9507  zdrafka.i45e22c050b21ffd4.jpg   {'name': 'point', 'cx': 215, 'cy': 406}
9508  zdrafka.i45e22c050b21ffd4.jpg   {'name': 'point', 'cx': 253, 'cy': 411}
9509  zdrafka.i45e22c050b21ffd4.jpg   {'name': 'point', 'cx': 217, 'cy': 456}
9510  zdrafka.i468a752693baf672.jpg   {'name': 'point', 'cx': 341, 'cy': 293}
9511  zdrafka.i468a752693baf672.jpg   {'name': 'point', 'cx': 573, 'cy': 384}
9512  zdrafka.i468a752693baf672.jpg   {'name': 'point', 'cx': 318, 'cy': 577}
9513  zdrafka.i8518d342ccbe71ed.jpg  {'name': 'point', 'cx': 1121, 'cy': 446}
9514  zdrafka.i8518d342ccbe71ed.jpg  {'name': 'point', 'cx': 1244, 'cy': 450}
9515  zdrafka.i8518d342ccbe71ed.jpg  {'name': 'point', 'cx': 1205, 'cy': 551}
9516  zdrafka.i56879edc3ad3d2c3.jpg   {'name': 'point', 'cx': 284, 'cy': 306}
9517  zdrafka.i56879edc3ad3d2c3.jpg   {'name': 'point', 'cx': 343, 'cy': 311}
9518  zdrafka.i56879edc3ad3d2c3.jpg   {'name': 'point', 'cx': 339, 'cy': 379}
9519  zdrafka.i525945daebd898fd.jpg  {'name': 'point', 'cx': 1147, 'cy': 674}
9520  zdrafka.i525945daebd898fd.jpg  {'name': 'point', 'cx': 1355, 'cy': 670}
9521  zdrafka.i525945daebd898fd.jpg  {'name': 'point', 'cx': 1162, 'cy': 925}
9522  zdrafka.ia06af248933e085a.jpg   {'name': 'point', 'cx': 948, 'cy': 353}
9523  zdrafka.ia06af248933e085a.jpg  {'name': 'point', 'cx': 1072, 'cy': 359}
9524  zdrafka.ia06af248933e085a.jpg   {'name': 'point', 'cx': 972, 'cy': 471}
9525      zoe.i88c518f87848e0c3.jpg   {'name': 'point', 'cx': 397, 'cy': 408}
9526      zoe.i88c518f87848e0c3.jpg   {'name': 'point', 'cx': 551, 'cy': 398}
9527      zoe.i88c518f87848e0c3.jpg   {'name': 'point', 'cx': 551, 'cy': 591}
9528      zoe.if55e75ef75d20e89.jpg   {'name': 'point', 'cx': 285, 'cy': 141}
9529      zoe.if55e75ef75d20e89.jpg    {'name': 'point', 'cx': 364, 'cy': 99}
9530      zoe.if55e75ef75d20e89.jpg   {'name': 'point', 'cx': 339, 'cy': 188}

[9531 rows x 2 columns]

In [80]:
df4

                           filename   lex  ley   rex  rey   nox   noy
0                 272100.272100.jpg   122  175   230  185   149   319
1               272100.272100_0.jpg   196  161   287  175   172   296
2               272100.272100_1.jpg   404  125   447  116   441   177
3               272100.272100_2.jpg   100   95   155  103   113   168
4               272100.272100_4.jpg   158   75   215   79   177   139
5               272100.272100_5.jpg   137   77   186   80   155   138
6                 272774.272774.jpg   167   97   244   94   187   157
7              272774.272774_0.jpeg   233   81   269   81   240   128
8               272774.272774_0.jpg   263  145   323  141   337   208
9               272774.272774_1.jpg   173   60   207   61   177    87
10              272774.272774_2.jpg   263  113   351  111   302   192
11              272774.272774_3.jpg   267  173   301  166   295   194
12               272986.272986.jpeg   237  149   303  153   293   209
13                272986.272986.jpg   261  119   317  114   297   166
14              272986.272986_0.jpg   270  147   321  148   307   209
15              272986.272986_1.jpg   252  157   315  157   257   239
16              272986.272986_2.jpg   239  117   295  123   252   185
17              272986.272986_5.jpg   337  131   363  129   353   160
18              272986.272986_6.jpg   231  138   275  135   248   195
19               274575.274575.jpeg   256  123   335   99   319   165
20                274575.274575.jpg   201  123   287  107   256   155
21             274575.274575_0.jpeg   362   93   397   92   388   122
22              274575.274575_0.jpg   178  116   261  119   199   179
23              274575.274575_1.jpg   225   64   273   59   250    87
24              274575.274575_2.jpg   213  142   267  151   217   193
25              274575.274575_3.jpg   151   79   185   83   155   108
26              274575.274575_4.jpg   274  116   311  120   293   138
27              276562.276562_0.jpg   234   33   273   41   243    53
28              276562.276562_2.jpg   268   93   349  108   293   173
29              276562.276562_3.jpg   220  125   292  137   243   181
...                             ...   ...  ...   ...  ...   ...   ...
3147    wanda.i0171f7c08242520e.jpg   869  507   934  510   904   589
3148    wanda.i438616269ef20c39.jpg  1089  369  1246  353  1158   523
3149    wanda.i205741786978b96f.jpg   681  538   961  518   832   782
3150    wanda.ia1709054582175dd.jpg   222  243   280  247   246   304
3151    wanda.ib0d43b8cf5ad1827.jpg   312  179   407  181   367   251
3152    wondy.i5fb699bb03819f71.jpg   842  256   946  272   867   387
3153    wondy.i866064a93ada1483.jpg   401  671   730  735   517  1031
3154    wondy.i9818578fa33807ae.jpg   837  444   982  457   931   642
3155    wondy.i20044997ab795a34.jpg   248  111   375  126   315   218
3156    wondy.iaab457cf355e8770.jpg   216  175   343  174   282   276
3157    wondy.ic2203269e5ea1318.jpg   184  200   299  202   179   291
3158    wondy.ifda43afc82acf13d.jpg   323  223   430  205   451   317
3159   yellow.i5bf20587770e5f6f.jpg   397  159   546  187   473   377
3160   yellow.i81b10d39354da8c3.jpg   300  347   359  299   412   400
3161   yellow.i605cacd519e6e2f4.jpg   468  218   536  264   455   319
3162   yellow.i9534bd3c6356af19.jpg   285  444   329  456   284   513
3163   yellow.ib7a72a8b8027c12d.jpg   273  189   465  234   358   420
3164   yellow.ic6c8a4ed167af717.jpg   468  375   579  372   503   491
3165     zack.i09e0b5c3da0e6b98.jpg   260  229   431  226   334   404
3166     zack.i30f2d0e11eea71bb.jpg   830  435  1027  450   919   627
3167     zack.i35873ce480b348e8.jpg   302  286   399  291   353   388
3168  zdrafka.i3f0a0c3d8ed8b719.jpg   401  208   465  194   447   258
3169  zdrafka.i45e22c050b21ffd4.jpg   215  406   253  411   217   456
3170  zdrafka.i468a752693baf672.jpg   341  293   573  384   318   577
3171  zdrafka.i8518d342ccbe71ed.jpg  1121  446  1244  450  1205   551
3172  zdrafka.i56879edc3ad3d2c3.jpg   284  306   343  311   339   379
3173  zdrafka.i525945daebd898fd.jpg  1147  674  1355  670  1162   925
3174  zdrafka.ia06af248933e085a.jpg   948  353  1072  359   972   471
3175      zoe.i88c518f87848e0c3.jpg   397  408   551  398   551   591
3176      zoe.if55e75ef75d20e89.jpg   285  141   364   99   339   188

[3177 rows x 7 columns]

In [24]:
import shutil

In [64]:
for root,dirs,files in os.walk("../../data/dogfacenet/images/"):
    if len(dirs)==0 and len(files)==0:
        print(root + ' ' + str(len(files)))
         #os.remove(root)
        #shutil.rmtree(root)

In [19]:
filenames = df4["filename"]
for i in range(len(filenames)):
    f = filenames[i]
    for s in range(len(f)):
        if f[s]=='.':
            break
    filenames[i] = f[s+1:]
filenames

c:\users\guillaume\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

0                  272100.jpg
1                272100_0.jpg
2                272100_1.jpg
3                272100_2.jpg
4                272100_4.jpg
5                272100_5.jpg
6                  272774.jpg
7               272774_0.jpeg
8                272774_0.jpg
9                272774_1.jpg
10               272774_2.jpg
11               272774_3.jpg
12                272986.jpeg
13                 272986.jpg
14               272986_0.jpg
15               272986_1.jpg
16               272986_2.jpg
17               272986_5.jpg
18               272986_6.jpg
19                274575.jpeg
20                 274575.jpg
21              274575_0.jpeg
22               274575_0.jpg
23               274575_1.jpg
24               274575_2.jpg
25               274575_3.jpg
26               274575_4.jpg
27               276562_0.jpg
28               276562_2.jpg
29               276562_3.jpg
                ...
3147    i0171f7c08242520e.jpg
3148    i438616269ef20c39.jpg
3149    i205741786978b96f.jpg
3150    ia1709054582175dd.jpg
3151    ib0d43b8cf5ad1827.jpg
3152    i5fb699bb03819f71.jpg
3153    i866064a93ada1483.jpg
3154    i9818578fa33807ae.jpg
3155    i20044997ab795a34.jpg
3156    iaab457cf355e8770.jpg
3157    ic2203269e5ea1318.jpg
3158    ifda43afc82acf13d.jpg
3159    i5bf20587770e5f6f.jpg
3160    i81b10d39354da8c3.jpg
3161    i605cacd519e6e2f4.jpg
3162    i9534bd3c6356af19.jpg
3163    ib7a72a8b8027c12d.jpg
3164    ic6c8a4ed167af717.jpg
3165    i09e0b5c3da0e6b98.jpg
3166    i30f2d0e11eea71bb.jpg
3167    i35873ce480b348e8.jpg
3168    i3f0a0c3d8ed8b719.jpg
3169    i45e22c050b21ffd4.jpg
3170    i468a752693baf672.jpg
3171    i8518d342ccbe71ed.jpg
3172    i56879edc3ad3d2c3.jpg
3173    i525945daebd898fd.jpg
3174    ia06af248933e085a.jpg
3175    i88c518f87848e0c3.jpg
3176    if55e75ef75d20e89.jpg
Name: filename, Length: 3177, dtype: object

In [33]:
len(filenames)

3177

In [54]:
import numpy as np

In [55]:
test = np.array(filenames)

In [56]:
filenames[0] in test

True

In [65]:
to_remove = []
c = 0
for root,dirs,files in os.walk("../../data/dogfacenet/images/"):
    for f in files:
        c += 1
        if not f in test: 
            to_remove += [f]
            
print(len(to_remove))
print(c)
print(c-len(to_remove))

0
3177
3177

In [60]:
for root,dirs,files in os.walk("../../data/dogfacenet/images/"):
    for f in files:
        c += 1
        if not f in test: 
            os.remove(root+'/'+f)

In [81]:
df4.to_csv(PATH+'labels/reformated_3177.csv')